---
name: App-ZofCMS-Plugin-DateSelector
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin to generate and "parse" <select>s for date/time input
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0111
  HTML::Template: 2.9
  Time::Local: 1.11
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::DateSelector:
    file: lib/App/ZofCMS/Plugin/DateSelector.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
